### ISSUE TITLE
artomator:all does not created nested directory for requests

### ISSUE THREAD

**Issue by frankpde** [pwweb/artomator#1]
When calling
`php artisan artomator:all Test/Subtest/Subsubtest/Class`
the corresponding request will be created as ValidateClass.php or not at all (depending on the depth of the namespace.

Calling the following command on the other hand produces a nested directory structure (according to the namespace):
`php artisan artomator:request Test/Subtest/Subsubtest/Class`

Also the following standard command produces a nested directory structure:
`php artisan make:request Test/Subtest/Subsubtest/Class`

**Expected Result**
./app/Http/Requests/Test/Subtest/Subsubtest/Class.php is created

**Actual Result**
./app/Http/Requests/ValidateClass.php is created (if namespace is Test/Class)
no file generated (if namespace is as above Test/Subtest/Subsubtest/Class)

**Comment by rabrowne85** [comment]
I've corrected this issue but in doing so, the name of the request class is without the Validate prefix.

See code in commit: afb03307939d064fbc0ee0607175ac15d476ff3c
