### ISSUE TITLE
Stub(s) missing documentation entities

### ISSUE THREAD

**Issue by frankpde** [pwweb/artomator#32]
Collection issue for stub adjustments to fix phpcs issues out of the box.

**Model**
_Missing member variable doc comment_ for $table, $dates, $fillable
_Missing short description in doc comment_ for linked tables (e.g. addresses for address type)

**Comment by rabrowne85** [comment]
Partial fix has been completed in: ab97f0b60c2c1cbd929e583688864ace24bf647f

Not possible to complete the others.

That being said it is possible if you know which other parts you are generally using you could manually add to the stub file that's published and then it will be used there after.
