### ISSUE TITLE
Class 'App\Http\Controllers\AppBaseController' not found 

### ISSUE THREAD

**Issue by frankpde** [pwweb/artomator#39]
The base controller class is not part of the generated files out of the graphql_scaffold.

Should include a check if the file exists, if not create it.

**Comment by rabrowne85** [comment]
This is a documentation issue.

For this to work you need to run the commands:
```bash
$ php artisan artomator:publish
$ php artisan ui bootstrap --auth
$ php artisan artomator.publish:layout
```

This will create the necessary files.

I have also updated the readme to be more prescriptive in how to install and copied some of the InfyOmLabs Documentation in to help.
