### ISSUE TITLE
Custom routes in json

### ISSUE THREAD

**Issue by frankpde** [pwweb/artomator#42]
Creating new models etc. overwrites custom routes placed between the artomator tags in web.php. Therefore need to also adjust the json to not delete these custom routes by mistake.

Currently get/post/ etc not supported.

**Comment by frankpde** [comment]
Example:
```php 
Route::get('/print/{id}', 'AccreditationController@print')->name('print');
```

**Comment by rabrowne85** [comment]
I've added a fix to the Artomator for the custom routes. Can you kindly test with your installation and custom routes? I suggest you copy your existing routes to a backup and then try adding the custom values to the json file.

**Comment by frankpde** [comment]
Partial success. In order to extend the general CRUD routes using ```php Route::resource() ``` need to be defined before calling ```php Route::resource() ```. Despite having the custom routes defined ahead of the resources in the json file, they get placed after the resource.
Additionally it would be good to have an artomator command that regenerates the routes from json

**Comment by rabrowne85** [comment]
Okay, that should be fairly simple.

- [ ] switch order of resource code and custom code in the generator (lines 148 onwards)
- [ ] add specific command file for routes based on other scaffold commands

**Comment by rabrowne85** [comment]
The ability to regenerate the routes is a bit of a hack. I'm not able to get it to work without having it require the Model name. As such you have to run it with `php artisan artomator.scaffold:routes Temp` and then type `exit`. Thoughts?
