### ISSUE TITLE
Rewrite of Installation Instructions

### ISSUE THREAD

**Issue by frankpde** [pwweb/artomator#59]
When running 
`artisan artomator:graphql_scaffold ModelName`

the stub file is no longer found:
`...vendor/infyomlabs/laravel-generator/templates/scaffold/views/blade_table_body.stub): Failed to open stream: No such file or directory`

**Comment by rabrowne85** [comment]
Have you published the template files before running the command?

**Comment by rabrowne85** [comment]
`$ php artisan artomator.publish:layout`

**Comment by rabrowne85** [comment]
I think the problem comes down to the installation instructions are unclear. I'm going to alter this issue to be more a rewrite of the instructions to make it clear what needs to happen in order for it to work.

**Comment by rabrowne85** [comment]
-[ ] Rewrite publish commands to trigger the sub-project artisan commands rather than duplicate the work
-[ ] Maybe add some questions to the installation commands to get user input about some of the options i.e. coreui/adminlte?
-[ ] Update installation instructions to suit.

**Comment by frankpde** [comment]
> Have you published the template files before running the command?

Yes

**Comment by rabrowne85** [comment]
Does the file exist at the location defined?

**Comment by rabrowne85** [comment]
Fixed in 92479fdd0c37dcb4fd97ebe72e0dbdcea92339cc
